# Generated by Django 3.2.7 on 2021-12-26 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='securedlist',
            name='email_id',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='securedlist',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
